- name: 'zsh installed'
  apt:
          name: zsh
          state: latest
          update_cache: yes
- name: 'developer group'
  group:
          name: developer
          state: present
- name: 'bill user'
  user:
          name: bill
          comment: Developer Bill
          shell: /bin/bash
          groups: developer
          append: yes
- name: 'jenkins user'
  user:
          name: jenkins
          comment: jenkins automation user
          shell: /bin/bash

